#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config/mongodb \
	/config/log

# Setup Mongodb
if [ ! -e "/config/mongodb.conf" ]; then
	cp /defaults/mongodb.conf /config/mongodb.conf
fi

# Setup Pritunl Zero
if [ ! -L /etc/pritunl-zero.json ]; then
	rm /config/pritunl-zero.json
	ln -s /config/pritunl-zero.json /etc/pritunl-zero.json
fi

# permissions
chown -R abc:abc \
	/config